name: OrthodoxCalendar
favicon: null
layout_spectrum: 0.052250096341595054
typography_spectrum: 0.8312762249261141
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7803971713874489
  lightness: 0.3988922517746687
  saturation: 0.951932308729738
  rhythmicContrast: 0.537255632923916
purpose: []
