name: OrthodoxCalendar
favicon: null
layout_spectrum: 0.9027
typography_spectrum: 0.8312762249261141
title: Orthodox Calendar Company
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7d8d9d'
    - '#010300'
    - '#7a6b56'
    - '#444442'
    - '#b47b6a'
  brandStrength: 0.5625
  lightness: 0.1875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
